-- Mariana -- a port of the Sublime Text "Mariana" color scheme.
--
-- The palette is Sublime's own (Mariana.sublime-color-scheme), and the scope
-- mapping was sampled from a Sublime screenshot so PHP/JS/Go read the same way:
--   * control keywords (use/class/function/const/return/new/if) -- purple
--   * storage modifiers (public/private/static/extends)         -- red
--   * method definitions -- cyan, method calls & types -- blue (italic types)
--   * parameters -- orange, locals -- foreground, operators -- red2

local p = {
  bg = '#303841', -- blue2
  bg_dark = '#2a3138', -- sidebar / non-current windows
  bg_darker = '#232a30', -- floats, sign column shadows
  bg_cursorline = '#3b434c',
  bg_highlight = '#46525c', -- current line number, matching paren
  bg_visual = '#4e5a65',
  bg_search = '#f9ae58',

  fg = '#d8dee9', -- white3
  fg_dim = '#a6acb9', -- blue6, accessors / punctuation
  fg_gutter = '#72787e',
  grey = '#647382',
  slate = '#596673', -- blue3

  red = '#ec5f66',
  red2 = '#f97b58', -- operators
  orange = '#f9ae58',
  yellow = '#fac761', -- orange3
  green = '#99c794',
  cyan = '#5fb4b4', -- blue5
  blue = '#6699cc',
  purple = '#c695c6',
  black = '#0d0f12',
}

vim.cmd.highlight 'clear'
if vim.fn.exists 'syntax_on' == 1 then
  vim.cmd.syntax 'reset'
end
vim.o.background = 'dark'
vim.g.colors_name = 'mariana'

local hl = vim.api.nvim_set_hl

local groups = {
  -- Editor UI
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg_darker },
  FloatBorder = { fg = p.slate, bg = p.bg_darker },
  FloatTitle = { fg = p.blue, bg = p.bg_darker, bold = true },
  ColorColumn = { bg = p.bg_dark },
  Conceal = { fg = p.grey },
  Cursor = { fg = p.bg, bg = p.fg },
  lCursor = { fg = p.bg, bg = p.fg },
  CursorIM = { fg = p.bg, bg = p.fg },
  CursorLine = { bg = p.bg_cursorline },
  CursorColumn = { bg = p.bg_cursorline },
  CursorLineNr = { fg = p.fg, bg = p.bg_highlight, bold = true },
  LineNr = { fg = p.fg_gutter },
  LineNrAbove = { fg = p.fg_gutter },
  LineNrBelow = { fg = p.fg_gutter },
  SignColumn = { fg = p.fg_gutter, bg = p.bg },
  FoldColumn = { fg = p.fg_gutter, bg = p.bg },
  Folded = { fg = p.fg_dim, bg = p.bg_dark },
  VertSplit = { fg = p.bg_darker },
  WinSeparator = { fg = p.bg_darker },
  Directory = { fg = p.blue },
  EndOfBuffer = { fg = p.bg },
  ErrorMsg = { fg = p.red, bold = true },
  WarningMsg = { fg = p.orange },
  MoreMsg = { fg = p.blue },
  ModeMsg = { fg = p.fg, bold = true },
  MsgArea = { fg = p.fg },
  MsgSeparator = { fg = p.slate },
  NonText = { fg = p.slate },
  Whitespace = { fg = p.slate },
  SpecialKey = { fg = p.slate },
  MatchParen = { fg = p.yellow, bg = p.bg_highlight, bold = true },
  Pmenu = { fg = p.fg, bg = p.bg_darker },
  PmenuSel = { fg = p.fg, bg = p.bg_visual },
  PmenuKind = { fg = p.blue, bg = p.bg_darker },
  PmenuKindSel = { fg = p.blue, bg = p.bg_visual },
  PmenuExtra = { fg = p.fg_dim, bg = p.bg_darker },
  PmenuExtraSel = { fg = p.fg_dim, bg = p.bg_visual },
  PmenuSbar = { bg = p.bg_dark },
  PmenuThumb = { bg = p.grey },
  Question = { fg = p.green },
  QuickFixLine = { bg = p.bg_visual },
  Search = { fg = p.black, bg = p.yellow },
  IncSearch = { fg = p.black, bg = p.orange },
  CurSearch = { fg = p.black, bg = p.orange },
  Substitute = { fg = p.black, bg = p.red2 },
  StatusLine = { fg = p.fg, bg = p.bg_dark },
  StatusLineNC = { fg = p.grey, bg = p.bg_dark },
  TabLine = { fg = p.fg_dim, bg = p.bg_dark },
  TabLineFill = { bg = p.bg_darker },
  TabLineSel = { fg = p.fg, bg = p.bg },
  Title = { fg = p.blue, bold = true },
  Visual = { bg = p.bg_visual },
  VisualNOS = { bg = p.bg_visual },
  WildMenu = { fg = p.black, bg = p.blue },
  WinBar = { fg = p.fg_dim, bg = p.bg },
  WinBarNC = { fg = p.grey, bg = p.bg },

  -- Diffs
  DiffAdd = { fg = p.green, bg = '#333f3c' },
  DiffChange = { fg = p.yellow, bg = '#3a3f45' },
  DiffDelete = { fg = p.red, bg = '#40343a' },
  DiffText = { fg = p.fg, bg = '#4b5058' },
  diffAdded = { fg = p.green },
  diffRemoved = { fg = p.red },
  diffChanged = { fg = p.yellow },
  diffFile = { fg = p.blue },
  diffLine = { fg = p.purple },
  diffIndexLine = { fg = p.fg_dim },

  -- Spelling
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.yellow, undercurl = true },
  SpellLocal = { sp = p.cyan, undercurl = true },
  SpellRare = { sp = p.purple, undercurl = true },

  -- Legacy syntax groups
  Comment = { fg = p.fg_dim, italic = true },
  Constant = { fg = p.orange },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.yellow },
  Boolean = { fg = p.yellow },
  Float = { fg = p.yellow },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.purple },
  Conditional = { fg = p.purple },
  Repeat = { fg = p.purple },
  Label = { fg = p.purple },
  Operator = { fg = p.red2 },
  Keyword = { fg = p.purple },
  Exception = { fg = p.purple },
  PreProc = { fg = p.purple },
  Include = { fg = p.purple },
  Define = { fg = p.purple },
  Macro = { fg = p.purple },
  PreCondit = { fg = p.purple },
  Type = { fg = p.blue, italic = true },
  StorageClass = { fg = p.red },
  Structure = { fg = p.red },
  Typedef = { fg = p.red },
  Special = { fg = p.cyan },
  SpecialChar = { fg = p.cyan },
  Tag = { fg = p.red },
  Delimiter = { fg = p.fg_dim },
  SpecialComment = { fg = p.fg_dim, italic = true },
  Debug = { fg = p.red },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Ignore = { fg = p.grey },
  Error = { fg = p.red },
  Todo = { fg = p.bg, bg = p.yellow, bold = true },

  -- Treesitter
  ['@comment'] = { link = 'Comment' },
  ['@comment.documentation'] = { fg = p.fg_dim, italic = true },
  ['@comment.error'] = { fg = p.red, italic = true },
  ['@comment.warning'] = { fg = p.orange, italic = true },
  ['@comment.note'] = { fg = p.cyan, italic = true },
  ['@comment.todo'] = { fg = p.yellow, italic = true },

  ['@keyword'] = { fg = p.purple },
  ['@keyword.function'] = { fg = p.purple },
  ['@keyword.operator'] = { fg = p.red2 },
  ['@keyword.return'] = { fg = p.purple },
  ['@keyword.conditional'] = { fg = p.purple },
  ['@keyword.repeat'] = { fg = p.purple },
  ['@keyword.exception'] = { fg = p.purple },
  ['@keyword.import'] = { fg = p.purple },
  ['@keyword.coroutine'] = { fg = p.purple },
  ['@keyword.debug'] = { fg = p.red },
  ['@keyword.directive'] = { fg = p.purple },
  ['@keyword.type'] = { fg = p.purple },
  -- storage modifiers (public/private/static/abstract/final/extends) are red
  ['@keyword.modifier'] = { fg = p.red },
  ['@keyword.storage'] = { fg = p.red },
  ['@storageclass'] = { fg = p.red },
  ['@attribute'] = { fg = p.yellow },
  ['@attribute.builtin'] = { fg = p.yellow },

  ['@operator'] = { fg = p.red2 },
  ['@punctuation.delimiter'] = { fg = p.fg_dim },
  ['@punctuation.bracket'] = { fg = p.fg },
  ['@punctuation.special'] = { fg = p.cyan },

  ['@string'] = { fg = p.green },
  ['@string.documentation'] = { fg = p.green },
  ['@string.escape'] = { fg = p.cyan },
  ['@string.regexp'] = { fg = p.cyan },
  ['@string.special'] = { fg = p.cyan },
  ['@string.special.url'] = { fg = p.cyan, underline = true },
  ['@string.special.path'] = { fg = p.green },
  ['@character'] = { fg = p.green },
  ['@character.special'] = { fg = p.cyan },
  ['@number'] = { fg = p.yellow },
  ['@number.float'] = { fg = p.yellow },
  ['@boolean'] = { fg = p.yellow },

  ['@constant'] = { fg = p.orange },
  ['@constant.builtin'] = { fg = p.yellow },
  ['@constant.macro'] = { fg = p.orange },

  ['@variable'] = { fg = p.fg },
  ['@variable.builtin'] = { fg = p.blue }, -- $this, self, super
  ['@variable.parameter'] = { fg = p.orange },
  ['@variable.parameter.builtin'] = { fg = p.orange },
  ['@variable.member'] = { fg = p.fg },
  ['@property'] = { fg = p.fg },
  ['@field'] = { fg = p.fg },

  -- definitions are cyan, calls are blue -- the way Sublime splits
  -- entity.name.function from meta.function-call
  ['@function'] = { fg = p.cyan },
  ['@function.builtin'] = { fg = p.blue },
  ['@function.call'] = { fg = p.blue },
  ['@function.macro'] = { fg = p.blue },
  ['@function.method'] = { fg = p.cyan },
  ['@function.method.call'] = { fg = p.blue },
  ['@constructor'] = { fg = p.blue, italic = true },

  ['@type'] = { fg = p.blue, italic = true },
  ['@type.builtin'] = { fg = p.blue, italic = true },
  ['@type.definition'] = { fg = p.orange }, -- the class being declared
  ['@type.inherited'] = { fg = p.cyan, italic = true }, -- extends/implements/use
  ['@type.qualifier'] = { fg = p.red },
  ['@module'] = { fg = p.fg },
  ['@module.builtin'] = { fg = p.fg },
  ['@namespace'] = { fg = p.fg },
  ['@label'] = { fg = p.purple },

  ['@tag'] = { fg = p.red },
  ['@tag.builtin'] = { fg = p.red },
  ['@tag.attribute'] = { fg = p.orange },
  ['@tag.delimiter'] = { fg = p.fg_dim },

  ['@markup.heading'] = { fg = p.blue, bold = true },
  ['@markup.heading.1'] = { fg = p.red, bold = true },
  ['@markup.heading.2'] = { fg = p.orange, bold = true },
  ['@markup.heading.3'] = { fg = p.yellow, bold = true },
  ['@markup.heading.4'] = { fg = p.green, bold = true },
  ['@markup.heading.5'] = { fg = p.cyan, bold = true },
  ['@markup.heading.6'] = { fg = p.purple, bold = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.underline'] = { underline = true },
  ['@markup.quote'] = { fg = p.fg_dim, italic = true },
  ['@markup.math'] = { fg = p.cyan },
  ['@markup.link'] = { fg = p.blue },
  ['@markup.link.label'] = { fg = p.cyan },
  ['@markup.link.url'] = { fg = p.fg_dim, underline = true },
  ['@markup.raw'] = { fg = p.green },
  ['@markup.raw.block'] = { fg = p.green },
  ['@markup.list'] = { fg = p.red2 },
  ['@markup.list.checked'] = { fg = p.green },
  ['@markup.list.unchecked'] = { fg = p.fg_dim },
  ['@diff.plus'] = { fg = p.green },
  ['@diff.minus'] = { fg = p.red },
  ['@diff.delta'] = { fg = p.yellow },

  -- LSP semantic tokens -- these are what actually paint PHP with intelephense,
  -- so they follow the same definition/call, parameter/local split.
  ['@lsp.type.class'] = { fg = p.blue, italic = true },
  ['@lsp.type.interface'] = { fg = p.blue, italic = true },
  ['@lsp.type.enum'] = { fg = p.blue, italic = true },
  ['@lsp.type.struct'] = { fg = p.blue, italic = true },
  ['@lsp.type.type'] = { fg = p.blue, italic = true },
  ['@lsp.type.typeParameter'] = { fg = p.blue, italic = true },
  ['@lsp.type.namespace'] = { fg = p.fg },
  ['@lsp.type.decorator'] = { fg = p.yellow },
  ['@lsp.type.enumMember'] = { fg = p.orange },
  ['@lsp.type.property'] = { fg = p.fg },
  ['@lsp.type.variable'] = { fg = p.fg },
  ['@lsp.type.parameter'] = { fg = p.orange },
  ['@lsp.type.function'] = { fg = p.blue },
  ['@lsp.type.method'] = { fg = p.blue },
  ['@lsp.type.keyword'] = { fg = p.purple },
  ['@lsp.type.modifier'] = { fg = p.red },
  ['@lsp.type.operator'] = { fg = p.red2 },
  ['@lsp.type.comment'] = {},
  ['@lsp.type.string'] = { fg = p.green },
  ['@lsp.type.number'] = { fg = p.yellow },
  ['@lsp.typemod.class.declaration'] = { fg = p.orange, italic = false },
  ['@lsp.typemod.interface.declaration'] = { fg = p.orange, italic = false },
  ['@lsp.typemod.enum.declaration'] = { fg = p.orange, italic = false },
  ['@lsp.typemod.struct.declaration'] = { fg = p.orange, italic = false },
  ['@lsp.typemod.function.declaration'] = { fg = p.cyan },
  ['@lsp.typemod.method.declaration'] = { fg = p.cyan },
  ['@lsp.typemod.function.definition'] = { fg = p.cyan },
  ['@lsp.typemod.method.definition'] = { fg = p.cyan },
  ['@lsp.typemod.variable.defaultLibrary'] = { fg = p.blue },
  ['@lsp.typemod.variable.readonly'] = { fg = p.orange },
  ['@lsp.typemod.variable.global'] = { fg = p.orange },
  ['@lsp.typemod.parameter.declaration'] = { fg = p.orange },
  ['@lsp.mod.readonly'] = {},
  ['@lsp.mod.deprecated'] = { strikethrough = true },

  -- Diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.orange },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red, bg = '#3a3239' },
  DiagnosticVirtualTextWarn = { fg = p.orange, bg = '#3b3a38' },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = '#333c47' },
  DiagnosticVirtualTextHint = { fg = p.cyan, bg = '#323e42' },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
  DiagnosticUnnecessary = { fg = p.grey },
  DiagnosticDeprecated = { sp = p.grey, strikethrough = true },

  -- LSP
  LspReferenceText = { bg = p.bg_highlight },
  LspReferenceRead = { bg = p.bg_highlight },
  LspReferenceWrite = { bg = p.bg_highlight, underline = true },
  LspSignatureActiveParameter = { fg = p.orange, bold = true },
  LspInlayHint = { fg = p.grey, bg = p.bg_dark, italic = true },
  LspCodeLens = { fg = p.grey, italic = true },

  -- gitsigns
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.yellow },
  GitSignsDelete = { fg = p.red },
  GitSignsAddInline = { bg = '#3b5245' },
  GitSignsChangeInline = { bg = '#4c4b3c' },
  GitSignsDeleteInline = { bg = '#4f3a41' },
  GitSignsCurrentLineBlame = { fg = p.grey, italic = true },

  -- telescope
  TelescopeNormal = { fg = p.fg, bg = p.bg_darker },
  TelescopeBorder = { fg = p.slate, bg = p.bg_darker },
  TelescopeTitle = { fg = p.bg, bg = p.blue, bold = true },
  TelescopePromptNormal = { fg = p.fg, bg = p.bg_dark },
  TelescopePromptBorder = { fg = p.bg_dark, bg = p.bg_dark },
  TelescopePromptTitle = { fg = p.bg, bg = p.red2, bold = true },
  TelescopePromptPrefix = { fg = p.red2 },
  TelescopePromptCounter = { fg = p.grey },
  TelescopeResultsTitle = { fg = p.bg_darker, bg = p.bg_darker },
  TelescopePreviewTitle = { fg = p.bg, bg = p.green, bold = true },
  TelescopeSelection = { fg = p.fg, bg = p.bg_visual },
  TelescopeSelectionCaret = { fg = p.red2, bg = p.bg_visual },
  TelescopeMultiSelection = { fg = p.orange },
  TelescopeMatching = { fg = p.yellow, bold = true },
  TelescopeResultsClass = { fg = p.blue },
  TelescopeResultsField = { fg = p.fg },
  TelescopeResultsComment = { fg = p.fg_dim },

  -- which-key
  WhichKey = { fg = p.red2 },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.grey },
  WhichKeyValue = { fg = p.grey },
  WhichKeyFloat = { bg = p.bg_darker },
  WhichKeyBorder = { fg = p.slate, bg = p.bg_darker },
  WhichKeyTitle = { fg = p.blue, bg = p.bg_darker },
  WhichKeyIcon = { fg = p.cyan },
  WhichKeyIconAzure = { fg = p.blue },
  WhichKeyIconBlue = { fg = p.blue },
  WhichKeyIconCyan = { fg = p.cyan },
  WhichKeyIconGreen = { fg = p.green },
  WhichKeyIconGrey = { fg = p.grey },
  WhichKeyIconOrange = { fg = p.orange },
  WhichKeyIconPurple = { fg = p.purple },
  WhichKeyIconRed = { fg = p.red },
  WhichKeyIconYellow = { fg = p.yellow },
  WhichKeyNormal = { bg = p.bg_darker },

  -- nvim-cmp
  CmpItemAbbr = { fg = p.fg },
  CmpItemAbbrDeprecated = { fg = p.grey, strikethrough = true },
  CmpItemAbbrMatch = { fg = p.yellow, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.yellow, bold = true },
  CmpItemMenu = { fg = p.grey, italic = true },
  CmpItemKindDefault = { fg = p.fg_dim },
  CmpItemKindText = { fg = p.fg },
  CmpItemKindMethod = { fg = p.red },
  CmpItemKindFunction = { fg = p.red },
  CmpItemKindConstructor = { fg = p.red },
  CmpItemKindField = { fg = p.cyan },
  CmpItemKindVariable = { fg = p.cyan },
  CmpItemKindClass = { fg = p.purple },
  CmpItemKindInterface = { fg = p.purple },
  CmpItemKindStruct = { fg = p.purple },
  CmpItemKindModule = { fg = p.blue },
  CmpItemKindProperty = { fg = p.cyan },
  CmpItemKindEnum = { fg = p.purple },
  CmpItemKindEnumMember = { fg = p.orange },
  CmpItemKindKeyword = { fg = p.purple },
  CmpItemKindSnippet = { fg = p.green },
  CmpItemKindColor = { fg = p.orange },
  CmpItemKindFile = { fg = p.blue },
  CmpItemKindFolder = { fg = p.blue },
  CmpItemKindConstant = { fg = p.orange },
  CmpItemKindReference = { fg = p.yellow },
  CmpItemKindOperator = { fg = p.red2 },
  CmpItemKindTypeParameter = { fg = p.purple },
  CmpItemKindEvent = { fg = p.yellow },
  CmpItemKindUnit = { fg = p.orange },
  CmpItemKindValue = { fg = p.orange },
  CmpItemKindTypeParameterDefault = { fg = p.purple },

  -- neo-tree
  NeoTreeNormal = { fg = p.fg, bg = p.bg_dark },
  NeoTreeNormalNC = { fg = p.fg, bg = p.bg_dark },
  NeoTreeEndOfBuffer = { fg = p.bg_dark, bg = p.bg_dark },
  NeoTreeWinSeparator = { fg = p.bg_darker, bg = p.bg_darker },
  NeoTreeVertSplit = { fg = p.bg_darker, bg = p.bg_darker },
  NeoTreeRootName = { fg = p.blue, bold = true },
  NeoTreeDirectoryName = { fg = p.fg },
  NeoTreeDirectoryIcon = { fg = p.blue },
  NeoTreeFileName = { fg = p.fg },
  NeoTreeFileIcon = { fg = p.fg_dim },
  NeoTreeFileNameOpened = { fg = p.cyan },
  NeoTreeIndentMarker = { fg = p.slate },
  NeoTreeExpander = { fg = p.grey },
  NeoTreeTitleBar = { fg = p.bg, bg = p.blue },
  NeoTreeCursorLine = { bg = p.bg_visual },
  NeoTreeDimText = { fg = p.grey },
  NeoTreeDotfile = { fg = p.grey },
  NeoTreeGitAdded = { fg = p.green },
  NeoTreeGitConflict = { fg = p.orange },
  NeoTreeGitDeleted = { fg = p.red },
  NeoTreeGitIgnored = { fg = p.grey },
  NeoTreeGitModified = { fg = p.blue },
  NeoTreeGitUntracked = { fg = p.grey },
  NeoTreeGitStaged = { fg = p.blue },
  NeoTreeSymbolicLinkTarget = { fg = p.purple },
  NeoTreeFloatBorder = { fg = p.slate, bg = p.bg_darker },
  NeoTreeFloatTitle = { fg = p.blue, bg = p.bg_darker },

  -- bufferline
  BufferLineFill = { bg = p.bg_darker },
  BufferLineBackground = { fg = p.grey, bg = p.bg_dark },
  BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true, italic = false },
  BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg_dark },
  BufferLineTab = { fg = p.grey, bg = p.bg_dark },
  BufferLineTabSelected = { fg = p.fg, bg = p.bg, bold = true },
  BufferLineTabClose = { fg = p.red, bg = p.bg_dark },
  BufferLineTabSeparator = { fg = p.bg_darker, bg = p.bg_dark },
  BufferLineTabSeparatorSelected = { fg = p.bg_darker, bg = p.bg },
  BufferLineSeparator = { fg = p.bg_darker, bg = p.bg_dark },
  BufferLineSeparatorSelected = { fg = p.bg_darker, bg = p.bg },
  BufferLineSeparatorVisible = { fg = p.bg_darker, bg = p.bg_dark },
  BufferLineIndicatorSelected = { fg = p.red2, bg = p.bg },
  BufferLineModified = { fg = p.green, bg = p.bg_dark },
  BufferLineModifiedSelected = { fg = p.green, bg = p.bg },
  BufferLineModifiedVisible = { fg = p.green, bg = p.bg_dark },
  BufferLineDuplicate = { fg = p.grey, bg = p.bg_dark, italic = true },
  BufferLineDuplicateSelected = { fg = p.fg_dim, bg = p.bg, italic = true },

  -- mini.nvim
  MiniStatuslineModeNormal = { fg = p.bg, bg = p.blue, bold = true },
  MiniStatuslineModeInsert = { fg = p.bg, bg = p.green, bold = true },
  MiniStatuslineModeVisual = { fg = p.bg, bg = p.purple, bold = true },
  MiniStatuslineModeReplace = { fg = p.bg, bg = p.red, bold = true },
  MiniStatuslineModeCommand = { fg = p.bg, bg = p.orange, bold = true },
  MiniStatuslineModeOther = { fg = p.bg, bg = p.cyan, bold = true },
  MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_darker },
  MiniStatuslineFilename = { fg = p.fg_dim, bg = p.bg_dark },
  MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_darker },
  MiniStatuslineInactive = { fg = p.grey, bg = p.bg_dark },
  MiniIndentscopeSymbol = { fg = p.slate },
  MiniIndentscopePrefix = { nocombine = true },
  MiniSurround = { fg = p.bg, bg = p.orange },
  MiniTrailspace = { bg = p.red },

  -- indent-blankline
  IblIndent = { fg = '#3a424b' },
  IblScope = { fg = p.slate },
  IblWhitespace = { fg = '#3a424b' },

  -- todo-comments
  TodoBgFIX = { fg = p.bg, bg = p.red, bold = true },
  TodoBgHACK = { fg = p.bg, bg = p.orange, bold = true },
  TodoBgNOTE = { fg = p.bg, bg = p.green, bold = true },
  TodoBgPERF = { fg = p.bg, bg = p.purple, bold = true },
  TodoBgTEST = { fg = p.bg, bg = p.cyan, bold = true },
  TodoBgTODO = { fg = p.bg, bg = p.blue, bold = true },
  TodoBgWARN = { fg = p.bg, bg = p.yellow, bold = true },
  TodoFgFIX = { fg = p.red },
  TodoFgHACK = { fg = p.orange },
  TodoFgNOTE = { fg = p.green },
  TodoFgPERF = { fg = p.purple },
  TodoFgTEST = { fg = p.cyan },
  TodoFgTODO = { fg = p.blue },
  TodoFgWARN = { fg = p.yellow },
  TodoSignFIX = { fg = p.red },
  TodoSignHACK = { fg = p.orange },
  TodoSignNOTE = { fg = p.green },
  TodoSignPERF = { fg = p.purple },
  TodoSignTEST = { fg = p.cyan },
  TodoSignTODO = { fg = p.blue },
  TodoSignWARN = { fg = p.yellow },

  -- diffview
  DiffviewNormal = { fg = p.fg, bg = p.bg_dark },
  DiffviewCursorLine = { bg = p.bg_visual },
  DiffviewStatusLine = { fg = p.fg, bg = p.bg_dark },
  DiffviewVertSplit = { fg = p.bg_darker, bg = p.bg_darker },
  DiffviewFilePanelTitle = { fg = p.blue, bold = true },
  DiffviewFilePanelCounter = { fg = p.orange, bold = true },
  DiffviewFilePanelFileName = { fg = p.fg },
  DiffviewFilePanelRootPath = { fg = p.grey },
  DiffviewFilePanelPath = { fg = p.grey },
  DiffviewFilePanelInsertions = { fg = p.green },
  DiffviewFilePanelDeletions = { fg = p.red },
  DiffviewStatusAdded = { fg = p.green },
  DiffviewStatusModified = { fg = p.blue },
  DiffviewStatusDeleted = { fg = p.red },
  DiffviewStatusRenamed = { fg = p.purple },
  DiffviewStatusUntracked = { fg = p.grey },
  DiffviewDim1 = { fg = p.slate },

  -- toggleterm
  ToggleTerm1FloatBorder = { fg = p.slate },
  ToggleTermNormal = { bg = p.bg },

  -- lazy.nvim / mason
  LazyNormal = { fg = p.fg, bg = p.bg_darker },
  LazyButton = { fg = p.fg, bg = p.bg_dark },
  LazyButtonActive = { fg = p.bg, bg = p.blue, bold = true },
  LazyH1 = { fg = p.bg, bg = p.blue, bold = true },
  LazyH2 = { fg = p.blue, bold = true },
  LazyProgressDone = { fg = p.green, bold = true },
  LazyProgressTodo = { fg = p.grey },
  LazySpecial = { fg = p.cyan },
  LazyCommit = { fg = p.orange },
  LazyReasonPlugin = { fg = p.purple },
  MasonNormal = { fg = p.fg, bg = p.bg_darker },
  MasonHeader = { fg = p.bg, bg = p.blue, bold = true },
  MasonHighlight = { fg = p.blue },
  MasonHighlightBlock = { fg = p.bg, bg = p.blue },
  MasonHighlightBlockBold = { fg = p.bg, bg = p.blue, bold = true },
  MasonMuted = { fg = p.grey },
  MasonMutedBlock = { fg = p.fg_dim, bg = p.bg_dark },
}

for group, opts in pairs(groups) do
  hl(0, group, opts)
end

-- :terminal palette
vim.g.terminal_color_0 = '#2a3138'
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_5 = p.purple
vim.g.terminal_color_6 = p.cyan
vim.g.terminal_color_7 = p.fg
vim.g.terminal_color_8 = p.grey
vim.g.terminal_color_9 = p.red2
vim.g.terminal_color_10 = p.green
vim.g.terminal_color_11 = p.orange
vim.g.terminal_color_12 = p.blue
vim.g.terminal_color_13 = p.purple
vim.g.terminal_color_14 = p.cyan
vim.g.terminal_color_15 = '#ffffff'
